[build-system]
requires = ["maturin>=1.12,<2.0"]
build-backend = "maturin"

[project]
name = "furas"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Rust",
    "Programming Language :: Python :: Implementation :: CPython",
    "Programming Language :: Python :: Implementation :: PyPy",
]
dynamic = ["version"]

[[tool.uv.index]]
name = "flea-gitlab"
url = "https://gitlab.com/api/v4/projects/60534972/packages/pypi"
publish-url = "https://gitlab.com/api/v4/projects/60534972/packages/pypi"
explicit = true
