from typing import Any, Final, final

@final
class ExtractedEl:
    def __str__(self, /) -> str: ...
    @property
    def attrs(self, /) -> dict: ...
    @property
    def tag(self, /) -> str: ...
    @property
    def text(self, /) -> list[str]: ...

class FieldSpec:
    @final
    class Field(FieldSpec):
        __match_args__: Final = ("selector", "regex")
        def __new__(cls, /, selector: str, regex: str |None = None) -> FieldSpec.Field: ...
        @property
        def regex(self, /) -> str |None: ...
        @property
        def selector(self, /) -> str: ...
    @final
    class Submodel(FieldSpec):
        __match_args__: Final = ("fields",)
        def __new__(cls, /, fields: dict[str, FieldSpec]) -> FieldSpec.Submodel: ...
        @property
        def fields(self, /) -> dict[str, FieldSpec]: ...

@final
class Model:
    @property
    def field_signatures(self, /) -> dict[str, Any]: ...
    @field_signatures.setter
    def field_signatures(self, /, value: dict[str, Any]) -> None: ...
    @staticmethod
    def from_json(json: str) -> Model: ...
    @property
    def group_signature(self, /) -> Any: ...
    @group_signature.setter
    def group_signature(self, /, value: Any) -> None: ...
    @property
    def normalisation(self, /) -> NormalisationOptions: ...
    @normalisation.setter
    def normalisation(self, /, value: NormalisationOptions) -> None: ...
    def to_json(self, /) -> str: ...

@final
class NormalisationOptions:
    @property
    def unwrap_text_tags(self, /) -> bool: ...
    @unwrap_text_tags.setter
    def unwrap_text_tags(self, /, value: bool) -> None: ...

def extract(model: "Model", html: "str | bytes") -> "dict[str, ExtractedEl | dict[str, ExtractedEl] | list[ExtractedEl]]": ...
def generate_model(html: "str", selectors: "dict[str, FieldSpec | str]") -> Model: ...
def sum_as_string(a: int, b: int) -> str: ...
